language: julia
os:
  - linux
  - windows
julia:
  - 1.1
  - 1.3
matrix:
  allow_failures:
    - julia: 1.3
notifications:
  email: false
after_success:
  - julia -e 'import Pkg; cd(Pkg.dir("BGHMM")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
